/*
Each new term in the Fibonacci sequence is
generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms
will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci
sequence whose values do not exceed four
million, find the sum of the even-valued terms.
*/

package sdegutishomework

/*import "fmt"*/

func Fib(ch chan int) {
  a := 1
  b := 1
  for {
    n := a + b
    a = b
    b = n
    /*fmt.Println(a, b)*/
    ch <- a
  }
}

func fibonacci(i int) int {
  ch := make(chan int)
  go Fib(ch)
  for j := 0; j < i; j++ {
    <-ch
  }
  return <-ch
}
